---
title: "NPSReportFigures"
format: html
editor: visual
---

Colors for plots: 1 color: #88CCEE 2 colors: #88CCEE, #117733 3+ colors: these 2, plus any below #88CCEE, #117733

```{r}
#scale_color_manual(values = c("#88CCEE","#44AA99","#117733", "#999933", "#DDCC77", "#CC6677", "#AA4499", "#882255", "#332288"))
```

```{r libraries}
library(tidyverse)
library(qdapTools)
library(naniar)
library(mapview)
library(rnaturalearth)
library(rnaturalearthdata)
```

```{r read in data}
litdata <- read.csv("~/GitHubRepos/CareyLabVT/Powell/Data/litdata_cleaned.csv")
```

A lot of columns should be numeric, doing that now.

```{r restructure df}
na_strings <- c("NA", "N A", "N / A", "N/A", "N/ A", "Not Available", "NOt available", "", "not reported", "NR")

litdata_na <- litdata %>%
  replace_with_na_all(condition = ~.x %in% na_strings)

num_columns <- c("lat_dd", "long_dd", "depth_mean_m", "depth_min_m", "volume_m3", "sa_km2", "sa_ha", "delta_water_level", "delta_wl_direction", "delta_magnitude", "tp_ug_l", "chla_ugL", "number_of_sites_within_the_reservoir")

#a handy-dandy little function to turn columns that can be numeric to numeric!
is_all_numeric <- function(x) {
  !any(is.na(suppressWarnings(as.numeric(na.omit(x))))) & is.character(x)
}
#make cols that can be numeric numeric
litdata_na <- litdata_na %>% 
  mutate_if(is_all_numeric,as.numeric)
#str(litdata_na)
```

```{r adding ecoli to map}

#Nauholzbach, Germany, 50.916864, 8.144386
#Kalltalsperre reservoir, Germany, 50.644337, 6.307951
#Wahnbachtalsperre, Germany, 50.816070, 7.303853
#Camp Far West, CA, 39.052992, -121.311600
#Englebright, CA, 39.247860, -121.268906
#Lake Kaweah, CA, 36.405734, -118.980447
#Lake Success, CA, 36.083058, -118.912487
#New Hogan Lake Reservoir, CA, 38.157251, -120.799045
#Woodward Reservoir, CA, 37.854409, -120.868778
#Bagre, Burkina Faso, 11.501867, -0.595604

new_lat <- c(50.916864, 50.644337, 50.816070, 39.052992, 39.247860, 36.405734, 36.083058, 38.157251, 37.854409, 11.501867)
new_long <- c(8.144386, 6.307951, 7.303853, -121.311600, -121.268906, -118.980447, -118.912487, -120.799045, -120.868778, -0.595604)

newlatlong <- data.frame(lat_dd = new_lat, long_dd = new_long)
combmap <- bind_rows(litdata_na, newlatlong)
```


```{r map}
litmap <- litdata_na %>% 
  subset(!is.na(long_dd)) %>% 
  mapview(xcol = "long_dd", ycol = "lat_dd", crs = 4269, grid = FALSE)

world <- ne_countries(scale = "medium", returnclass = "sf")

my_countries <- c("Russia", "South Korea", "China", "Brazil", "Spain", "United States of America", "Burkina Faso", "Argentina", "Lebanon", "Vietnam", "Canada", "Israel", "Croatia", "Netherlands", "Estonia", "Italy", "Turkey", "Germany")

new_world <- mutate(world, fill = ifelse(sovereignt %in% c(my_countries), "yes", "no"))

litdata_map <- combmap %>% 
   mutate(mapvals = ifelse(((!is.na(phyto_response_wl_decrease)|!is.na(phyto_response_wl_increase)) & (!is.na(cyano_response_wl_decrease)|!is.na(cyano_response_wl_increase))), "Both",
                           ifelse(!is.na(phyto_response_wl_decrease)|!is.na(phyto_response_wl_increase), "Phytoplankton", 
                                 ifelse(!is.na(cyano_response_wl_decrease)|!is.na(cyano_response_wl_increase), "Cyanobacteria",
                                        ifelse(study_id == "Song 2023"|study_id== "Huang 2023", "Selective withdrawal", "Pathogen"))))) %>% 
  mutate(mapvals = ifelse(is.na(mapvals), "Pathogen", mapvals))

sitemap <- new_world %>% ggplot(fill = fill) +
    geom_sf(data = new_world, aes(fill = factor(fill))) +
  scale_fill_manual(values = c("white", "#88CCEE"), name = "Countries")+
    geom_point(data = litdata_map, aes(x = long_dd, y = lat_dd, shape = as.factor(mapvals), color = as.factor(mapvals)), size = 2) + 
  scale_color_manual(values = c("black", "black", "#CC6677", "black", "black"), name = "Variable") +
  scale_shape_manual(values = c(16, 16, 18, 16, 16), name = "Variable")+
  ylab("Latitude") + 
  xlab("Longitude") +
    theme(text = element_text(size = 12),
        axis.text.x = element_text(hjust = 1, size = 12), 
        axis.title.y=element_text(angle=0, vjust = .5))+
  theme_bw() +
    theme(text = element_text(size = 12),
        axis.text.x = element_text(hjust = 1, size = 12), 
        axis.title.y=element_text(angle=90, vjust = .5), 
        legend.position="none")
sitemap

ggsave("~/GitHubRepos/CareyLabVT/Powell/Plots/LitReview/NPSReport/sitemap.jpg", plot = sitemap, height = 4, width = 6.5, units = "in")
```

```{r bar plots}
#management concerns
litdata_na_expand <- litdata_na %>% 
  cbind(mtabulate(strsplit(litdata_na$sampling_months, "; "))) %>% 
  cbind(mtabulate(strsplit(litdata_na$mgmt_concerns, "; "))) %>% 
  rename(concern_drawdown = drawdown, 
         concern_flooding = flooding, 
         concern_drought = drought, 
         concern_waterlevelfluctuation = "water level fluctuation") %>% 
  cbind(mtabulate(strsplit(litdata_na$mgmt_strat, "; "))) %>% 
  rename(strat_drawdown = drawdown, 
         strat_episw = "epilimnion selective withdrawal", 
         strat_metasw = "metalimnion selective withdrawal", 
         strat_hyposw = "hypolimnion selective withdrawal", 
         strat_refill = "refill",
         strat_flushing = "hydraulic flushing")

mgmt_concerns <- c("concern_drought", "concern_drawdown", "concern_waterlevelfluctuation", "concern_flooding")

concerns <- litdata_na_expand %>% 
  select(all_of(mgmt_concerns)) %>% 
  summarise(Flooding = sum(concern_flooding == "1"), 
            Drought = sum(concern_drought == "1"),
            "Water level\n fluctuation" = sum(concern_waterlevelfluctuation == "1"), 
            Drawdown = sum(concern_drawdown == "1")) %>% 
  pivot_longer(everything(),  names_to = "concern", values_to = "count")
            
mgmtconcerns <- concerns %>% 
  ggplot(aes(x = concern, y = count, label = count)) + 
  # geom_col(position = "dodge", fill = "#88CCEE") +
  geom_col(position = "dodge", fill = "#DDCC77") +
  geom_text(position = position_dodge(width = 0.9),
            hjust = .5, vjust = 1.2, size = 4, color = "black") + 
  xlab("Management Concern") +
  ylab("Number of Papers") +  
  theme_bw() +
  theme(text = element_text(size = 12),
        axis.text.x = element_text(angle = 0, hjust = .5, size = 10))

mgmtconcerns
ggsave("~/GitHubRepos/CareyLabVT/Powell/Plots/LitReview/NPSReport/managementconcerns.png", plot = mgmtconcerns, height = 3, width = 6.5, units = "in")

#management strategies
mgmtstrat <- c("strat_drawdown", "strat_episw", "strat_flushing", "strat_refill")

mgmtstrat <- litdata_na_expand %>% 
  select(all_of(mgmtstrat)) %>% 
  summarise("Selective\n withdrawal" = sum(strat_episw == "1"), 
            "Drawdown" = sum(strat_drawdown == "1"), 
            "Flushing" = sum(strat_flushing == "1"), 
            "Refill" = sum(strat_refill == "1")) %>% 
  pivot_longer(everything(),  names_to = "strategy", values_to = "count")

mgmtstrats <- mgmtstrat %>% 
  ggplot(aes(x = factor(strategy, c("Drawdown", "Refill", "Flushing", "Selective\n withdrawal")), y = count, label = count)) + 
    geom_col(position = "dodge", fill = "#DDCC77") +
  geom_text(position = position_dodge(width = 0.9),
            hjust = 0.5, vjust = 1.2, color = "black", size = 4) + 
    xlab("Management Strategy") +
  ylab("Number of papers") + 
  theme_bw()+
  theme(text = element_text(size = 12),
        axis.text.x = element_text(angle = 0, size = 10))

mgmtstrats
ggsave("~/GitHubRepos/CareyLabVT/Powell/Plots/LitReview/NPSReport/managementstrategies.png", plot = mgmtstrats, height = 3, width = 6.5, units = "in")
```

```{r bar plot responses}
na_bin <- litdata_na %>%
  mutate(cyano_response_wl_up = ifelse(cyano_response_wl_increase == "not significant", "Not significant",
                                ifelse(cyano_response_wl_increase == "decrease", " Decrease", 
                                ifelse(cyano_response_wl_increase == "increase", " Increase", 
                               ifelse(cyano_response_wl_increase == "shift", "Shift to \n cyanobacteria", 
                              ifelse(cyano_response_wl_increase == "other", "Other", NA)))))) %>% 
    mutate(cyano_response_wl_down = ifelse(cyano_response_wl_decrease == "not significant", "Not significant", 
                                ifelse(cyano_response_wl_decrease == "decrease", "Decrease", 
                                ifelse(cyano_response_wl_decrease == "increase", "Increase", 
                               ifelse(cyano_response_wl_decrease == "shift", "Shift to \n cyanobacteria", NA))))) %>% 
    mutate(phyto_response_wl_up = ifelse(phyto_response_wl_increase == "not significant", " Not significant", 
                                ifelse(phyto_response_wl_increase == "decrease", " Decrease", 
                                ifelse(phyto_response_wl_increase == "increase", " Increase", 
                               ifelse(phyto_response_wl_increase == "shift", " Shift",
                              ifelse(phyto_response_wl_increase == "mixed response", " Other", NA)))))) %>% 
    mutate(phyto_response_wl_down = ifelse(phyto_response_wl_decrease == "not significant", "Not significant", 
                                ifelse(phyto_response_wl_decrease == "decrease", "Decrease", 
                                ifelse(phyto_response_wl_decrease == "increase", "Increase", 
                               ifelse(phyto_response_wl_decrease == "shift", "Shift to\n cyanobacteria", 
                               ifelse(phyto_response_wl_decrease == "other", "Other", NA))))))
  

phyto_decreasewl <- na_bin %>% 
  subset(!is.na(phyto_response_wl_down)) %>% 
  #replace_with_na(replace = list(phyto_response_wl_decrease = c("NA"))) %>% 
  #select(!is.na(binary_expand$phyto_response_wl_decrease)) %>% 
  ggplot(aes(x= factor(phyto_response_wl_down, c("Increase", "Decrease", "Not significant","Shift to\n cyanobacteria", "Other")))) + 
  geom_bar(fill = "#117733") +
  xlab("Phytoplankton response to water level decrease") +
  ylab("Number of waterbodies") +
  geom_text(aes(label = ..count..), stat = "count", vjust = 1.2, size = 4, colour = "white") + 
    theme_bw() +
  theme(text = element_text(size = 12),
        axis.text.x = element_text(angle = 0, size = 10))

#ggsave("phyto_decreasewl.jpg", plot = phyto_decreasewl, height = 8, width = 8, units = "in")

phyto_increasewl <- na_bin %>% 
  subset(!is.na(phyto_response_wl_up)) %>%
  #select(!is.na(binary_expand$phyto_response_wl_decrease)) %>% 
  ggplot(aes(x=factor(phyto_response_wl_up, c(" Increase", " Decrease", " Not significant", " Other")))) + 
  geom_bar(fill = "#117733") + 
  xlab("Phytoplankton response to water level increase")+
  ylab("Number of waterbodies") +
  geom_text(aes(label = ..count..), stat = "count", vjust = 1.2, size = 4, colour = "white") + 
    theme_bw() +
  theme(text = element_text(size = 12),
        axis.text.x = element_text(angle = 0, hjust = 0.5, size = 10))

cyano_decreasewl <- na_bin %>% 
  subset(!is.na(cyano_response_wl_down)) %>%
  #select(!is.na(binary_expand$phyto_response_wl_decrease)) %>% 
  ggplot(aes(x=factor(cyano_response_wl_down, c("Increase", "Decrease", "Not significant", "Shift to \n cyanobacteria")))) + 
  geom_bar(fill = "#88CCEE") +
  xlab("Cyanobacteria response to water level decrease") +
  #xlab("") +
  ylab("Number of waterbodies") +
  geom_text(aes(label = ..count..), stat = "count", vjust = 1.2, size = 4, colour = "black") + 
    theme_bw() +
  theme(text = element_text(size = 12),
        axis.text.x = element_text(angle = 0, size = 10))


cyano_increasewl <- na_bin %>% 
  subset(!is.na(cyano_response_wl_up)) %>%
  #select(!is.na(binary_expand$phyto_response_wl_decrease)) %>% 
  ggplot(aes(x=factor(cyano_response_wl_up, c(" Increase", " Decrease")))) + 
  geom_bar(fill = "#88CCEE") + 
  xlab("Cyanobacteria response to water level increase") + 
  ylab("Number of waterbodies") +
  geom_text(aes(label = ..count..), stat = "count", vjust = 1.2, size = 4, colour = "black") + 
    theme_bw() +
  theme(text = element_text(size = 12),
        axis.text.x = element_text(angle = 0, hjust = 0.5, size = 10))

phyto_decreasewl
phyto_increasewl
cyano_decreasewl
cyano_increasewl

ggsave("~/GitHubRepos/CareyLabVT/Powell/Plots/LitReview/NPSReport/phyto_decreasewl.jpg", plot = phyto_decreasewl, height = 3, width = 6.5, units = "in")
ggsave("~/GitHubRepos/CareyLabVT/Powell/Plots/LitReview/NPSReport/phyto_increasewl.jpg", plot = phyto_increasewl, height = 3, width = 6.5, units = "in")
ggsave("~/GitHubRepos/CareyLabVT/Powell/Plots/LitReview/NPSReport/cyano_decreasewl.jpg", plot = cyano_decreasewl, height = 3, width = 6.5, units = "in")
ggsave("~/GitHubRepos/CareyLabVT/Powell/Plots/LitReview/NPSReport/cyano_increasewl.jpg", plot = cyano_increasewl, height = 3, width = 6.5, units = "in")
```

```{r more bar plots}
#trophic status

trophic_status <- litdata_na %>% 
  mutate(trophic_status_condensed = ifelse(trophic_status_combined == "hypertrophic", "Hypereutrophic", 
                                           ifelse(trophic_status_combined == "meso-eutrophic"|trophic_status_combined == "eutrophic", "Eutrophic",
                                                  ifelse(trophic_status_combined == "mesotrophic"|trophic_status_combined =="oligo-mesotrophic", "Mesotrophic",
                                                         ifelse(trophic_status_combined == "oligotrophic", "Oligotrophic",
                                                                ifelse(is.na(trophic_status_combined), "Not reported", trophic_status_combined)))))) %>% 
  replace_na(list(trophic_status_condensed ="Not reported")) %>% 
  #subset(!is.na(trophic_status_condensed)) %>%
  #select(!is.na(binary_expand$phyto_response_wl_decrease)) %>% 
  ggplot(aes(x= factor(trophic_status_condensed, c("Hypereutrophic", "Eutrophic","Mesotrophic", "Oligotrophic", "Not reported")))) + 
 geom_bar(fill = "#DDCC77") + 
  xlab("Trophic status") + 
  ylab("Number of reservoirs") +
  geom_text(aes(label = ..count..), stat = "count", vjust = 1.2, size = 4, colour = "black") + 
    theme_bw() +
  theme(text = element_text(size = 12),
        axis.text.x = element_text(angle = 45, hjust = 1, size = 10))
trophic_status

studytype <- litdata_map %>% ggplot(aes(x= factor(mapvals, c("phytoplankton", "cyanobacteria", "both", "selective withdrawal", "pathogen")))) + 
 geom_bar(fill = "#88CCEE") + 
  xlab("Data collected") + 
  ylab("Number of reservoirs") +
  geom_text(aes(label = ..count..), stat = "count", vjust = 1.5, size = 5, colour = "black") +
    theme_bw() +
  theme(text = element_text(size = 12),
        axis.text.x = element_text(angle = 45, hjust = 1, size= 10))
studytype

# ggsave("~/GitHubRepos/CareyLabVT/Powell/Plots/LitReview/NPSReport/studytype.jpg", plot = studytype, height = 3, width = 6.5, units = "in")
ggsave("~/GitHubRepos/CareyLabVT/Powell/Plots/LitReview/NPSReport/trophic_status.jpg", plot = trophic_status, height = 3, width = 6.5, units = "in")
```

```{r logistic regression}
boxplotdata2 <- litdata_na %>%  #changed 0 and 1 for phyto_wl_increase :( after poster print :(
  mutate(prop_delta_wl = delta_wl_direction/depth_max_m) %>% 
    mutate(phyto_binary_increase = ifelse(phyto_response_wl_increase == "not significant", 0, 
                                ifelse(phyto_response_wl_increase == "decrease", 0, 
                                ifelse(phyto_response_wl_increase == "increase", 1, NA)))) %>% 
  mutate(phyto_binary_decrease = ifelse(phyto_response_wl_decrease == "not significant", 0, 
                                ifelse(phyto_response_wl_decrease == "decrease", 0, 
                                ifelse(phyto_response_wl_decrease == "increase", 1, NA)))) %>%
  # mutate(combined_phyto_response_text = phyto_response_wl_decrease %>% 
  #          is.na() %>% 
  #          ifelse(phyto_response_wl_increase, phyto_response_wl_decrease)) %>% 
    mutate(combined_phyto_response_binary = phyto_binary_decrease %>% 
           is.na() %>% 
           ifelse(phyto_binary_increase, phyto_binary_decrease)) %>% 
    mutate(cyano_binary_increase = ifelse(cyano_response_wl_increase == "not significant", 0, 
                                ifelse(cyano_response_wl_increase == "decrease", 0, 
                                ifelse(cyano_response_wl_increase == "increase", 1, NA)))) %>% 
  mutate(cyano_binary_decrease = ifelse(cyano_response_wl_decrease == "not significant", 0, 
                                ifelse(cyano_response_wl_decrease == "decrease", 0, 
                                ifelse(cyano_response_wl_decrease == "increase", 1, NA)))) %>%
  # mutate(combined_phyto_response_text = phyto_response_wl_decrease %>% 
  #          is.na() %>% 
  #          ifelse(phyto_response_wl_increase, phyto_response_wl_decrease)) %>% 
    mutate(combined_cyano_response_binary = cyano_binary_decrease %>% 
           is.na() %>% 
           ifelse(cyano_binary_increase, cyano_binary_decrease)) %>% 
  mutate(cyano_response_wl_up = ifelse(cyano_response_wl_increase == "not significant", "Not significant", 
                                ifelse(cyano_response_wl_increase == "decrease", "Decrease ", 
                                ifelse(cyano_response_wl_increase == "increase", "Increase ", 
                               ifelse(cyano_response_wl_increase == "shift", "Shift", NA))))) %>% 
    mutate(cyano_response_wl_down = ifelse(cyano_response_wl_decrease == "not significant", "Not significant", 
                                ifelse(cyano_response_wl_decrease == "decrease", "Decrease", 
                                ifelse(cyano_response_wl_decrease == "increase", "Increase", 
                               ifelse(cyano_response_wl_decrease == "shift", "Shift to \n cyanobacteria", NA))))) %>% 
  mutate(combined_cyano_response = cyano_response_wl_down %>% 
           is.na() %>% 
           ifelse(cyano_response_wl_up, cyano_response_wl_down)) %>% 
    mutate(phyto_response_wl_up = ifelse(phyto_response_wl_increase == "not significant", "Not significant", 
                                ifelse(phyto_response_wl_increase == "decrease", "Decrease ", 
                                ifelse(phyto_response_wl_increase == "increase", "Increase ", 
                               ifelse(phyto_response_wl_increase == "shift", "Shift", NA))))) %>% 
    mutate(phyto_response_wl_down = ifelse(phyto_response_wl_decrease == "not significant", "Not significant", 
                                ifelse(phyto_response_wl_decrease == "decrease", "Decrease", 
                                ifelse(phyto_response_wl_decrease == "increase", "Increase", 
                               ifelse(phyto_response_wl_decrease == "shift", "Shift to\n Cyanobacteria\n dominated\n community", NA))))) %>% 
  mutate(combined_phyto_response = phyto_response_wl_down %>% 
           is.na() %>% 
           ifelse(phyto_response_wl_up, phyto_response_wl_down))

# phytoresponsebinary <- boxplotdata2 %>% 
#   ggplot(aes(x = prop_delta_wl, y = combined_phyto_response_binary)) + 
#   geom_point() + geom_smooth(method = "glm", 
#               method.args = list(family = "binomial"),
#               se = FALSE) + 
#   ylab("Phytoplankton response to changes in water level") + 
#   xlab("Proportion water level change") +
#     theme_bw() +
#   theme(text = element_text(size = 20),
#         axis.text.x = element_text(angle = 45, hjust = 1, size = 16))
# 
# cyanoresponsebinary <- boxplotdata2 %>% 
#   ggplot(aes(x = prop_delta_wl, y = combined_cyano_response_binary)) + 
#   geom_point() + geom_smooth(method = "glm", 
#               method.args = list(family = "binomial"),
#               se = FALSE) + 
#   ylab("Cyanobacterial response to changes in water level") + 
#   xlab("Proportion water level change") +   
#   theme_bw() +
#   theme(text = element_text(size = 20),
#         axis.text.x = element_text(angle = 45, hjust = 1, size = 16))

# phytoresponsebinary
# cyanoresponsebinary
# ggsave("~/GitHubRepos/CareyLabVT/Powell/Plots/LitReview/NPSReport/phytoresponsebinary.png", plot = phytoresponsebinary, height = 6, width = 10, units = "in")
# ggsave("~/GitHubRepos/CareyLabVT/Powell/Plots/LitReview/NPSReport/cyanoresponsebinary.png", plot = cyanoresponsebinary, height = 6, width = 10, units = "in")

```

```{r}
cyanodecreasedata <- boxplotdata2 %>% 
  select(prop_delta_wl, combined_cyano_response, combined_cyano_response_binary, study_id) %>% 
  filter(!is.na(prop_delta_wl)) %>%
  filter(!is.na(combined_cyano_response_binary)) %>% 
  filter(prop_delta_wl<0) %>% 
  rename(response_binary = combined_cyano_response_binary, 
         response = combined_cyano_response) %>% 
  mutate(type = "cyano")

cyanoincreasedata <- boxplotdata2 %>% 
  select(prop_delta_wl, combined_cyano_response, combined_cyano_response_binary, study_id) %>% 
  filter(!is.na(prop_delta_wl)) %>%
  filter(!is.na(combined_cyano_response_binary)) %>% 
  filter(prop_delta_wl>0) %>% 
  rename(response_binary = combined_cyano_response_binary, 
         response = combined_cyano_response) %>% 
  mutate(type = "cyano")

phytoincreasedata <- boxplotdata2 %>% 
  select(prop_delta_wl, combined_phyto_response, combined_phyto_response_binary, study_id) %>% 
  filter(!is.na(prop_delta_wl)) %>% 
  filter(!is.na(combined_phyto_response_binary)) %>% 
  filter(prop_delta_wl>0) %>% 
  rename(response_binary = combined_phyto_response_binary, 
         response = combined_phyto_response) %>% 
  mutate(type = "phyto")

phytodecreasedata <- boxplotdata2 %>% 
  select(prop_delta_wl, combined_phyto_response, combined_phyto_response_binary, study_id) %>% 
  filter(!is.na(prop_delta_wl)) %>% 
  filter(!is.na(combined_phyto_response_binary)) %>% 
  filter(prop_delta_wl<0) %>% 
  rename(response_binary = combined_phyto_response_binary, 
         response = combined_phyto_response) %>% 
  mutate(type = "phyto")
  
cyanodata <- boxplotdata2 %>% 
  select(prop_delta_wl, combined_cyano_response, combined_cyano_response_binary, study_id) %>% 
  filter(!is.na(prop_delta_wl)) %>%
  filter(!is.na(combined_cyano_response_binary)) %>% 
  # filter(prop_delta_wl<0) %>% 
  rename(response_binary = combined_cyano_response_binary, 
         response = combined_cyano_response) %>% 
  mutate(type = "cyano")

phytodata <- boxplotdata2 %>% 
  select(prop_delta_wl, combined_phyto_response, combined_phyto_response_binary, study_id) %>% 
  filter(!is.na(prop_delta_wl)) %>% 
  filter(!is.na(combined_phyto_response_binary)) %>% 
  # filter(prop_delta_wl<0) %>% 
  rename(response_binary = combined_phyto_response_binary, 
         response = combined_phyto_response) %>% 
  mutate(type = "phyto")
# logregdata <- rbind(cyanoincreasedata, cyanodecreasedata, phytoincreasedata, phytodecreasedata)
logregdata <- rbind(cyanodata, phytodata)
#"#7A524B","#3C7F29","#8DBAE9"

test <- logregdata %>% ggplot(aes(x = prop_delta_wl, y = response_binary, color = as.factor(type), shape = as.factor(type))) +
  scale_color_manual(values = c("#88CCEE", "#117733"), name = "")+
  scale_shape_manual(values = c(8, 20)) +
  geom_point(size = 3) +
  geom_smooth(method = "glm", 
              method.args = list(family = "binomial"),
              se = FALSE, linewidth = 3) + 
  #geom_jitter()+
 ylab("Response to changes in water level") + 
  xlab("Proportion water level change") + 
  theme_bw() +
  theme(axis.text.x = element_text(hjust = 1, size = 10), 
        axis.title.y=element_text(angle=90, vjust = .5, size = 12), 
        legend.title=element_blank())
test

ggsave("~/GitHubRepos/CareyLabVT/Powell/Plots/LitReview/NPSReport/combinedlogregression.png", plot = test, height = 3, width = 6.5, units = "in")
```

```{r logistic reg stats}
logregform <-  glm(formula=response_binary ~ prop_delta_wl, data=logregdata, family=binomial)
summary(logregform)

logregdata_phyto <- logregdata %>% subset(type == "phyto")
logregdata_cyano <- logregdata %>% subset(type == "cyano")

logregform_phyto <-  glm(formula=response_binary ~ prop_delta_wl, data=logregdata_phyto, family=binomial)
summary(logregform_phyto)

logregform_cyano <-  glm(formula=response_binary ~ prop_delta_wl, data=logregdata_cyano, family=binomial)
summary(logregform_cyano)
```
